development:
  cloud_name: dkfx04d8y
  api_key: '377739272157659'
  api_secret: TN7Y2dEosXBhggPpfAzuRjgRjx4
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dkfx04d8y
  api_key: '377739272157659'
  api_secret: TN7Y2dEosXBhggPpfAzuRjgRjx4
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dkfx04d8y
  api_key: '377739272157659'
  api_secret: TN7Y2dEosXBhggPpfAzuRjgRjx4
  enhance_image_tag: true
  static_image_support: false